### PR TITLE
fix: partial revert

### PR DESCRIPTION
**Pull request by timcadman**
After using the new version of DSI, Stuart has pointed out the following two issues:

V1.6.0: `errors <- datashield.errors()` returned a list with the errors
V1.7.0:  `errors <- datashield.errors()` prints the errors and but does not save assign them to an object

He also suggested that it would be more conservative for the default behaviour to be that in V1.6.0 (ie printing a message "there are datashield errors ... )" rather than printing the error.

## Changes made
- `datashield.errors()` now behaves as in version 1.6.0 in that errors can be assigned in plain text to an object
- If no global options are set the default behaviour is that of V1.6.0 - a message is displayed saying 'there are datashield errors'
- The first time that `datashield.errors()` is called in a session an information message is displayed informing the user of the option to now return errors directly.

## How to test
- Install version from this branch
- Log in to a datashield session where the connections object is called 'conns'

### Test 1
```
datashield.assign.expr(conns, symbol = "G", expr = "doesntwork")
datashield.errors()
```
Check that errors are displayed along with the following message: 
ℹ Errors can now be automatically printed, rather than requiring a call to datashield.errors().
ℹ To enable this behavior, run options(datashield.return_errors = TRUE)
This message is displayed once per session.

### Test 2
```
errors <- datashield.errors()
errors
```
Check that the object 'error' contains a list with the errors in unformatted text

### Test 3
```
options(datashield.return_errors = TRUE)
datashield.assign.expr(conns, symbol = "G", expr = "doesntwork")
```
Check that errors are printed immediately

### Test 4
```
options(datashield.return_errors = FALSE)
datashield.assign.expr(conns, symbol = "G", expr = "doesntwork")
```
Check that the message "there are datashield errors" is displayed

### Test 5
```
datashield.errors()
```
Check that the errors are displayed but no information message

### CODE REVIEW

**Comment by StuartWheater** [comment]
The ".inform_once", in "R/datashield.errors.R", appears to need the addition of a "}" at the end of the method [to pass devtools::checked()].

**Comment by StuartWheater** [comment]
The "datashield.errors", in "R/datashield.errors.R", appears to be missing a parameter "type"

**Comment by StuartWheater** [comment]
Could update "RoxygenNote" to latest version 7.3.2 in "DESCRIPTION"

**Review by StuartWheater — CHANGES_REQUESTED** [review]
- The ".inform_once", in "R/datashield.errors.R", appears to need the addition of a "}" at the end of the method [to pass devtools::checked()].

- The "datashield.errors", in "R/datashield.errors.R", appears to be missing a parameter "type"

- Could update "RoxygenNote" to latest version 7.3.2 in "DESCRIPTION"

- Could run "devtools::build_site()" to regenerate 'docs'

**Comment by StuartWheater** [comment]
Could run "devtools::build_site()" to regenerate 'docs'

**Review by StuartWheater — APPROVED** [review]

**Comment by ymarcon** [comment]
Merged but I  have renamed your `datashield.return_errors` option to `datashield.errors.print` for consistency with other options. See details in the README.

**Pull request merged**
